[package]
name = "flipper_core"
version = "0.1.0"
authors = [ "George Morgan <george@george-morgan.com>",
            "Nick Mosher <nicholastmosher@gmail.com>" ]
edition = "2018"

[lib]
name = "flipper_core"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.0"
log = "0.4.1"
failure = "0.1.1"
libusb = "0.3.0"
lazy_static = "1.2.0"
